GET http://localhost:3001/api/persons/3

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Test4",
    "number": "08"
}

###
DELETE http://localhost:3001/api/persons/66c250853fe00e5cbc8dde/
